-- MySQL Script generated by MySQL Workbench
-- Wed 25 May 2016 06:03:11 PM AMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parica_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parica_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parica_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `parica_db` ;

-- -----------------------------------------------------
-- Table `parica_db`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`contato` (
  `ct_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `ct_lagradouro` VARCHAR(45) NOT NULL,
  `ct_numero` CHAR(4) NOT NULL,
  `ct_bairro` VARCHAR(45) NULL,
  `ct_cidade` VARCHAR(45) NOT NULL,
  `ct_estado` VARCHAR(2) NULL,
  `ct_email` VARCHAR(255) NULL,
  `ct_tel_1` CHAR(11) NULL COMMENT '00000000000',
  `ct_tel_2` CHAR(11) NULL,
  PRIMARY KEY (`ct_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`turma` (
  `tu_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `tu_nome` VARCHAR(45) NOT NULL,
  `tu_turno` CHAR(1) NOT NULL COMMENT '0 = Matutino\n1 = Vespertino\n2 = Noturno',
  `tu_ano` CHAR(4) NOT NULL,
  PRIMARY KEY (`tu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`aluno` (
  `al_id` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
  `al_nome_aluno` VARCHAR(60) NOT NULL,
  `al_nome_mae` VARCHAR(60) NOT NULL,
  `al_nome_pai` VARCHAR(60) NOT NULL,
  `al_cpf_aluno` CHAR(11) NULL,
  `al_cpf_mae` CHAR(11) NOT NULL,
  `al_cpf_pai` CHAR(11) NULL,
  `al_rg_aluno` CHAR(9) NULL,
  `al_rg_mae` CHAR(9) NOT NULL,
  `al_rg_pai` CHAR(9) NULL,
  `al_cert_nasc` CHAR(32) NOT NULL,
  `al_pcd` INT(1) UNSIGNED NOT NULL COMMENT '0 = Não\n1 = Sim',
  `al_naturalidade` VARCHAR(45) NULL,
  `al_nacionalidade` VARCHAR(45) NULL,
  `al_obs` TEXT NULL,
  `al_img_aluno` VARCHAR(50) NULL,
  `al_dt_nasc` DATE NOT NULL,
  `al_dt_matricula` DATETIME NULL,
  `al_ct_id` INT(5) ZEROFILL NOT NULL,
  `turma_tu_id` INT(5) ZEROFILL NOT NULL,
  `al_orgExp` CHAR(4) NULL,
  `al_situacao` INT(1) NULL COMMENT '1 = NOVO\n2 = TRANSFERIDO\n3 = DESISTENTE\n4 = REPETENTE',
  `al_estadoCivil` INT(1) NULL COMMENT '1 = SOLTEIRO\n2 = CASADO\n3 = DIVORCIADO\n4 = VIÚVO\n5 = ESTÁVEL',
  PRIMARY KEY (`al_id`, `turma_tu_id`),
  UNIQUE INDEX `al_cpf_aluno_UNIQUE` (`al_cpf_aluno` ASC),
  UNIQUE INDEX `al_cpf_mae_UNIQUE` (`al_cpf_mae` ASC),
  UNIQUE INDEX `al_cpf_pai_UNIQUE` (`al_cpf_pai` ASC),
  UNIQUE INDEX `al_rg_aluno_UNIQUE` (`al_rg_aluno` ASC),
  UNIQUE INDEX `al_rg_mae_UNIQUE` (`al_rg_mae` ASC),
  UNIQUE INDEX `al_rg_pai_UNIQUE` (`al_rg_pai` ASC),
  UNIQUE INDEX `al_cert_nasc_UNIQUE` (`al_cert_nasc` ASC),
  INDEX `fk_aluno_contato1_idx` (`al_ct_id` ASC),
  INDEX `fk_aluno_turma1_idx` (`turma_tu_id` ASC),
  CONSTRAINT `fk_aluno_contato1`
    FOREIGN KEY (`al_ct_id`)
    REFERENCES `parica_db`.`contato` (`ct_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_tu_id`)
    REFERENCES `parica_db`.`turma` (`tu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `parica_db`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`colaborador` (
  `co_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `co_nome` VARCHAR(45) NULL,
  `co_cpf` VARCHAR(45) NULL,
  `co_rg` VARCHAR(45) NULL,
  PRIMARY KEY (`co_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`cargo` (
  `ca_id` INT(5) ZEROFILL NOT NULL,
  `ca_nome` VARCHAR(60) NULL,
  `ca_salario` DECIMAL(4,2) NULL,
  `ca_turno` CHAR(3) NULL COMMENT '0 = Matutino\n1 = Vespertino\n2 = Noturno',
  PRIMARY KEY (`ca_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`materia` (
  `ma_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `ma_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ma_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`colaborador_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`colaborador_cargo` (
  `cc_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `cc_co_id` INT(5) ZEROFILL NOT NULL,
  `cc_ca_id` INT(5) ZEROFILL NOT NULL,
  PRIMARY KEY (`cc_id`, `cc_co_id`, `cc_ca_id`),
  INDEX `fk_colaborador_has_cargo_cargo1_idx` (`cc_ca_id` ASC),
  INDEX `fk_colaborador_has_cargo_colaborador1_idx` (`cc_co_id` ASC),
  CONSTRAINT `fk_colaborador_has_cargo_colaborador1`
    FOREIGN KEY (`cc_co_id`)
    REFERENCES `parica_db`.`colaborador` (`co_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_has_cargo_cargo1`
    FOREIGN KEY (`cc_ca_id`)
    REFERENCES `parica_db`.`cargo` (`ca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`materia_colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`materia_colaborador` (
  `mc_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `mc_ma_id` INT(5) ZEROFILL NOT NULL,
  `mc_co_id` INT(5) ZEROFILL NOT NULL,
  PRIMARY KEY (`mc_id`, `mc_ma_id`, `mc_co_id`),
  INDEX `fk_materia_has_colaborador_colaborador1_idx` (`mc_co_id` ASC),
  INDEX `fk_materia_has_colaborador_materia1_idx` (`mc_ma_id` ASC),
  CONSTRAINT `fk_materia_has_colaborador_materia1`
    FOREIGN KEY (`mc_ma_id`)
    REFERENCES `parica_db`.`materia` (`ma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_has_colaborador_colaborador1`
    FOREIGN KEY (`mc_co_id`)
    REFERENCES `parica_db`.`colaborador` (`co_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`boletim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`boletim` (
  `bo_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `bo_n1` DECIMAL(2,2) NULL,
  `bo_n2` DECIMAL(2,2) NULL,
  `bo_n3` DECIMAL(2,2) NULL,
  `bo_n4` DECIMAL(2,2) NULL,
  `bo_f1` DECIMAL(2,2) NULL,
  `bo_f2` DECIMAL(2,2) NULL,
  `bo_f3` DECIMAL(2,2) NULL,
  `bo_f4` DECIMAL(2,2) NULL,
  `bo_ma_id` INT(5) ZEROFILL NOT NULL,
  `bo_al_id` INT(6) ZEROFILL NOT NULL,
  PRIMARY KEY (`bo_id`),
  INDEX `fk_boletim_materia1_idx` (`bo_ma_id` ASC),
  INDEX `fk_boletim_aluno1_idx` (`bo_al_id` ASC),
  CONSTRAINT `fk_boletim_materia1`
    FOREIGN KEY (`bo_ma_id`)
    REFERENCES `parica_db`.`materia` (`ma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boletim_aluno1`
    FOREIGN KEY (`bo_al_id`)
    REFERENCES `parica_db`.`aluno` (`al_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`materia_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`materia_turma` (
  `mt_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `mt_ma_id` INT(5) ZEROFILL NOT NULL,
  `mt_tu_id` INT(5) ZEROFILL NOT NULL,
  PRIMARY KEY (`mt_id`, `mt_ma_id`, `mt_tu_id`),
  INDEX `fk_materia_has_turma_turma1_idx` (`mt_tu_id` ASC),
  INDEX `fk_materia_has_turma_materia1_idx` (`mt_ma_id` ASC),
  CONSTRAINT `fk_materia_has_turma_materia1`
    FOREIGN KEY (`mt_ma_id`)
    REFERENCES `parica_db`.`materia` (`ma_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_has_turma_turma1`
    FOREIGN KEY (`mt_tu_id`)
    REFERENCES `parica_db`.`turma` (`tu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parica_db`.`declaracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parica_db`.`declaracoes` (
  `dc_id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `dc_nome` VARCHAR(45) NULL,
  `dc_text` TEXT NULL,
  PRIMARY KEY (`dc_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
